<a href="https://colab.research.google.com/github/gabrielawad/talleresGoogleColab/blob/main/Taller_12_CVXPY_matricial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## «*La gente tiende a olvidar sus deberes, pero recuerda sus derechos*».
### [Indira Gandhi](https://es.wikipedia.org/wiki/Indira_Gandhi)

# Taller 12 CVXPY matrices

En este taller aprenderá los conceptos básicos de Python 3 relativos a la librería CVXPY.

CVXPY  **no es una librería nativa** de Python por lo que **requiere ser instalada antes de ser invocada**. Sin embargo, esta librería sí está preinstalada en Google Colaboratory por lo que basta invocarla para poder usar sus funcionalidades.

Puede consultar mayor información en: [CVXPY](https://www.cvxpy.org/)


# Tipos de variables en CVXPY

CVXPY permite crear variables, parámetros escalares y arreglos (vectores y matrices); para tal efecto sigue la sintaxis (formatos) de la librería [NumPy](https://docs.scipy.org/doc/numpy/index.html).


In [ ]:
# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear una variable de tipo escalar
a = cvx.Variable()

# Crear una variable escalar no negativa
a_no_negativa = cvx.Variable(nonneg = True)

# Crear una variable escalar entera
a_entera = cvx.Variable(integer=True)

# Crear una variable escalar boolena
a_booleana = cvx.Variable(boolean =True)

# Crear un parámetro con un valor específico
b = 8

# Crear una variable de tipo arreglo (m,1). Contiene "m" filas y una columna
c = cvx.Variable((3,1))

# Crear una parámetro de tipo arreglo (m,1) con valores específicos
d = [3, 2, 4]

# Crear una variable de tipo arreglo (m,n). Contiene "m" filas y "n" columnas
e = cvx.Variable((4, 3))

# Crear un parámetro de tipo arreglo (m,n) con valores específicos
e = [[5, 6, 7],[2, 6, 9],[3, 8, 5],[9, 5,1 ]]

# Multiplicaciones en CVXPY

In [16]:
# Importar las librerías que se van a utilizar
import cvxpy as cvx

# Crear un parámetro escalar
par_esc_1 = cvx.Parameter()
par_esc_1.value = 2

par_esc_2 = cvx.Parameter()
par_esc_2.value = 5

# Multiplicar los parámetros escalares
prod_esc = par_esc_1 * par_esc_2
print("El prducto de los escalares es: \n ", prod_esc.value)

# Crear un parámetro vectorial
par_vec_1 = cvx.Parameter((2,2))
# |1 3|
# |2 4|
par_vec_1.value = [[1,2],[3,4]]

par_vec_2 = cvx.Parameter((2,2))
# |5 7|
# |6 8|
par_vec_2.value = [[5,6],[7,8]]

# Multiplicar un escalar por un vector
prod_esc_vec = par_esc_1 * par_vec_2
print("Producto de un escalar y un vector: \n", prod_esc_vec.value)

# Multiplicar los parámetros vectoriales
prod_arreglos = par_vec_1 @ par_vec_2
print("Producto de dos arreglos:\n", prod_arreglos.value)

# Multiplicar los parámetros vectoriales con la función prod
prod_punto_arreglos = cvx.multiply(par_vec_1, par_vec_2)
print("Producto punto de dos arreglos:\n", prod_punto_arreglos.value)

# Sumar el producto punto de dos arreglos
suma_arreglos = cvx.sum(prod_punto_arreglos)
print("Suma del producto punto de dos arreglos:\n", suma_arreglos.value)

El prducto de los escalares es: 
  10
Producto de un escalar y un vector: 
 [[10. 14.]
 [12. 16.]]
Producto de dos arreglos:
 [[23. 31.]
 [34. 46.]]
Producto punto de dos arreglos:
 [[ 5. 21.]
 [12. 32.]]
Suma del producto punto de dos arreglos:
 70.0


# Resolver un ejercicio en forma algebraica y en forma matricial

Ejercicio a resolver:

Minimizar 3x + 8y

sujeto a:

x + y >= 50

x - y <= 20

x, y no negativos


## Solución algebráica

In [18]:
# Este código presenta la solución de un ejercicio de forma algebraica

print ("Solución algebraica")
# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables a optimizar
x = cvx.Variable()
y = cvx.Variable()

# Definir la función objetivo
obj_00 = cvx.Minimize(3*x + 8*y)

# Establecer las restricciones
restricciones_00 = [
x + y >= 50,
x - y <= 20,
x >= 0,
y >= 0
]

# Configurar el problema
prob_00 = cvx.Problem(obj_00, restricciones_00)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00.solve()

# Mostrar el estado de la solución algebraica
print("Estado de la solución algebraica:", prob_00.status)

# Mostrar el valor óptimo de la función objetivo algebraica
print("Valor óptimo de la función objetivo algebraica:", prob_00.value)

# Mostrar los valores óptimos de las variables de decisión algebraica
print("Valores óptimos de las variables de decisión algebraica:",
      x.value, y.value, "\n")

Solución algebraica
Estado de la solución algebraica: optimal
Valor óptimo de la función objetivo algebraica: 224.9999996816037
Valores óptimos de las variables de decisión algebraica: 35.00000000022704 14.999999960115321 



## Solución matricial

El siguiente código resuelve el mismo ejercicio de forma matricial.

Ejercicio a resolver:

Minimizar 3x + 8y

sujeto a:

x + y >= 50

x - y <= 20

x, y no negativos

Para resolverlo se realizan los siguientes ajustes:

*  se crea un arreglo con las variables de decisión (**x**)
*  se define un arreglo con los coeficientes de costos (**c**)
*  se define el arreglo con la matriz de coeficientes técnicos (**A**)
*  se define el arreglo con las condiciones límites o restricciones (**b**)

**Nota importante**: antes de definir **A** y **b** se llevan las inecuaciones a una forma estándar. Es decir que todas queden en el mismo sentido.

**inecuaciones iniciales**

x + y >= 50

x  - y <= 20

x >= 0

y >= 0

Es necesario transformar la segunda inecuación en una del tipo **mayor igual**, para lograrlo se multiplican ambos lados de la inecuación por -1.

**inecuaciones transformadas**

   x + y >=  50
   
    
 \-x + y >= -20

 x >= 0

 y >= 0

De donde:

A=[[1, -1, 1, 0], [1, 1, 0, 1]]

b= [50, -20, 0, 0]




In [17]:
# Este código presenta la solución de un ejercicio de forma matricial

print ("Solución matricial")
# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
arr_x = cvx.Variable((2,1))

# Crear el arreglo con los coeficientes de costos
arr_c =[[3],[8]]

# Definir la función objetivo
obj_00_arr = cvx.Minimize(arr_c @ arr_x)

# Establecer el arreglo los coeficientes técnicos
arr_A=[[1, -1, 1, 0], [1, 1, 0, 1]]

# Crear un arreglo con condiciones límites (restricciones)
arr_b= [[50, -20, 0, 0]]

# Establecer las restricciones en forma matricial
arr_restricciones = [arr_A @ arr_x >= arr_b]

# Configurar el problema
prob_00_arr = cvx.Problem(obj_00_arr, arr_restricciones)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00_arr.solve()

# Mostrar el estado de la solución matricial
print("Estado de la solución matricial:", prob_00_arr.status)

# Mostrar el valor óptimo de la función objetivo matricial
print("Valor óptimo de la función objetivo matricial:", prob_00_arr.value)

# Mostrar los valores óptimos de las variables de decisión matricial
print("Valores óptimos de las variables de decisión matricial:",
      arr_x[0].value, arr_x[1].value, "\n")

Solución matricial
Estado de la solución matricial: optimal
Valor óptimo de la función objetivo matricial: 224.9999996816037
Valores óptimos de las variables de decisión matricial: [35.] [14.99999996] 



## Solución matricial utilizando NumPy

In [19]:
# Este código presenta la solución de un ejercicio de forma matricial
# utilizando NumPy

print ("Solución matricial utilizando NumPy")
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
arr_x_np = cvx.Variable((2,1))

# Crear el arreglo con los coeficientes de costos
arr_c_np = np.array([3, 8])

# Definir la función objetivo
obj_00_arr_np = cvx.Minimize(arr_c_np @ arr_x_np)

# Establecer el arreglo los coeficientes técnicos
arr_A_np = np.array([[1, 1], [-1, 1],[1,0], [0, 1]])

# Crear un arreglo con condiciones límites (restricciones)
arr_b_np= np.array([[50], [-20], [0], [0]])
#arr_b_np= np.array([50, -20, 0, 0]).reshape((4,1))

# Establecer las restricciones en forma matricial
arr_restricciones_np = [arr_A_np @ arr_x_np >= arr_b_np]

# Configurar el problema
prob_00_arr_np = cvx.Problem(obj_00_arr_np, arr_restricciones_np)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00_arr_np.solve()

# Mostrar el estado de la solución matricial
print("Estado de la solución matricial:", prob_00_arr_np.status)

# Mostrar el valor óptimo de la función objetivo matricial
print("Valor óptimo de la función objetivo matricial:", prob_00_arr_np.value)

# Mostrar los valores óptimos de las variables de decisión matricial
print("Valores óptimos de las variables de decisión matricial:",
      arr_x_np[0].value, arr_x_np[1].value, "\n")

Solución matricial utilizando NumPy
Estado de la solución matricial: optimal
Valor óptimo de la función objetivo matricial: 224.9999996816037
Valores óptimos de las variables de decisión matricial: [35.] [14.99999996] 



## Solución matricial cargando los datos desde una url

In [20]:
# Este código presenta la solución de un ejercicio de forma matricial
# cargando los datos desde una url

print ("Solución matricial obteniendo datos desde una url")
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
arr_url_x = cvx.Variable((2,1))

# Crear el arreglo con los coeficientes de costos
arr_url_c = cvx.Parameter((2,1))

# Cargar coeficientes de costos desde una url
# Establecer la ruta de los coeficientes de costos
ruta_c ='https://docs.google.com/spreadsheets/d/e/2PACX-1vRFLriI2aliprDmDCCKXKz\
8dBQFZGSrw7We_bq6tQKXPdDpAffIjtZ9fau9HhXJIPfelNZQ1hpBY9fH/pub?output=csv'

# Cargar los coeficientes de costos con el método np.loadtxt()
arr_url_c = np.loadtxt(ruta_c, delimiter=",", dtype=float)
print("Los coeficientes de costos son: \n", arr_url_c, "\n")

# Definir la función objetivo
obj_00_arr_url = cvx.Minimize(arr_url_c @ arr_url_x)

# Crear el arreglo con los coeficientes técnicos
arr_url_A = cvx.Parameter((4,2))

# Cargar los coeficientes técnicos desde una url
# Establecer la ruta de los coeficientes técnicos
ruta_A ='https://docs.google.com/spreadsheets/d/e/2PACX-1vSwX-JTXjqsm2fM7pJmvw\
UbSUb8QQdhCPscJTSLLe_FS8NSsTR_WeqPbzOz40SVo_gnVr5EU4PN9P_r/pub?output=csv'

# Cargar el arreglo con los coeficientes técnicos con el método np.loadtxt()
arr_url_A = np.loadtxt(ruta_A, delimiter=",", dtype=float)
print("Los coeficientes técnicos son: \n", arr_url_A, "\n")

# Crear el arreglo con las restricciones
arr_url_b = cvx.Parameter((4,1))

# Cargar las restricciones desde una url
# Establecer la ruta de las restricciones
ruta_b='https://docs.google.com/spreadsheets/d/e/2PACX-1vSILEeSPXklgIr36YnJe\
Kw1Ab4tFYF4x04IxqhCrDfyYzsqxmPEHjz1ZjKeGQh2IcELgDzu0sskTXCF/pub?output=csv'

# Cargar el arreglo con las restricciones con el método np.loadtxt()
arr_url_b= np.loadtxt(ruta_b, delimiter=",", dtype=float).reshape((4,1))
print("Las restricciones son: \n", arr_url_b, "\n")

# Establecer las restricciones en forma matricial
arr_url_restricciones = [arr_url_A @ arr_url_x >= arr_url_b]

# Configurar el problema
prob_00_arr_url = cvx.Problem(obj_00_arr_url, arr_url_restricciones)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00_arr_url.solve()

# Mostrar el estado de la solución matricial
print("Estado de la solución matricial:", prob_00_arr_url.status)

# Mostrar el valor óptimo de la función objetivo matricial
print("Valor óptimo de la función objetivo matricial:", prob_00_arr_url.value)

# Mostrar los valores óptimos de las variables de decisión matricial
print("Valores óptimos de las variables de decisión matricial:",
      arr_url_x[0].value, arr_url_x[1].value, "\n")

Solución matricial obteniendo datos desde una url
Los coeficientes de costos son: 
 [3. 8.] 

Los coeficientes técnicos son: 
 [[ 1.  1.]
 [-1.  1.]
 [ 1.  0.]
 [ 0.  1.]] 

Las restricciones son: 
 [[ 50.]
 [-20.]
 [  0.]
 [  0.]] 

Estado de la solución matricial: optimal
Valor óptimo de la función objetivo matricial: 224.9999996816037
Valores óptimos de las variables de decisión matricial: [35.] [14.99999996] 



## Ejemplo 01: Industrias Felicidad

Industrias Felicidad S. A. produce mezcla para tortas utilizando un molino. Para producir una tonelada de mezcla para tortas se requieren dos horas de trabajo del molino y tres horas de trabajo en la sección de empacado.

El molino solo puede estar en funcionamiento diez horas diarias, mientras que la sección de empacado puede trabajar hasta 16 horas diarias.

Cada tonelada de mezcla para tortas se vende a 250.000 pesos y tiene un costo de producción de 180.000 pesos.

Calcule la producción diaria de mezcla para tortas para maximizar el ingreso por ventas.

In [ ]:
# Solución algebraica

# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear la variable de decisión
qTorta = cvx.Variable()


# Definir la función objetivo para maximizar el ingreso
objIndFel = cvx.Maximize(250000*qTorta)

# Establecer las restricciones
restriccionesIndFel = [

# Restricción de capacidad de molino
2*qTorta <= 10,

# Restricción de capacidad de empacado
3*qTorta<= 16,

# Restricción de no negatividad
qTorta >= 0
]

# Configurar el problema
probIndFel = cvx.Problem(objIndFel, restriccionesIndFel)

# Obtener el valor óptimo
probIndFel.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", probIndFel.status)

# Mostrar el valor óptimo de la función objetivo
print("Ingreso máximo:", probIndFel.value)

# Mostrar los valores óptimos de las variables de decisión
print("Cantidad de mezcla de tortas que maximiza el ingreso por ventas:",
      qTorta.value)

In [ ]:
# Solución matricial
# Escriba acá el código para resolver de forma matricial el ejercicio anterior


## Ejemplo 02: Compañía Reddy Mikks

Tomado del libro de [TAHA, 2012](https://fad.unsa.edu.pe/bancayseguros/wp-content/uploads/sites/4/2019/03/investigacic3b3n-de-operaciones-9na-edicic3b3n-hamdy-a-taha-fl.pdf), ejemplo 2.1-1 página 13.

Reddy Mikks se propone determinar la combinación óptima de pinturas para interiores y exteriores que maximice la utilidad diaria total.

Variables de decisión:

Xi = toneladas producidas diariamente de la pintura tipo i.
Sea i {1 = para exteriores, 2 = para interiores}

Función objetivo:
Max Z = 5000X1 + 4000X2

Restricciones:

Consumo de M1 para ambas pinturas:  		6X1 + 4X2 ≤ 24

Consumo de M2 para ambas pinturas:	 	X1 + 2X2 ≤ 6

Límites de demanda diaria:			X2 – X1  ≤ 1

Límites de demanda diaria para pintura de interiores:		X2  ≤ 2

No negatividad:  			 Xi ≥ 0 para todo i


In [ ]:
# Ejemplo 2.1-1 del libro de TAHA (Compañía Reddy Mikks)
# Solución algebraica

# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables de decisión
exterior = cvx.Variable()
interior = cvx.Variable()


# Definir la función objetivo para maximizar el ingreso
objRM = cvx.Maximize(5000*exterior + 4000*interior)

# Establecer las restricciones
restriccionesRM = [

# Consumo de materia prima M1
6*exterior + 4*interior <= 24,

# Consumo de materia prima M2
1*exterior + 2*interior <= 6,

# Límites de demanda diaria
interior - exterior <= 1,

# Demanda diaria para pintura de interiores
interior <= 2,

# Restricción de no negatividad
exterior >= 0,

interior >= 0

]

# Configurar el problema
probRM = cvx.Problem(objRM, restriccionesRM)

# Obtener el valor óptimo
probRM.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", probRM.status)

# Mostrar el valor óptimo de la función objetivo sin aproximaciones
print("Utilidad máxima SIN aproximaciones:", probRM.value)

# Mostrar el valor óptimo de la función objetivo aproximado a dos decimales
print("Utilidad máxima aproximada a dos decimales:", "%.2f"% probRM.value)

# Mostrar los valores óptimos de las variables de decisión
print("Toneladas de pinturas para exteriores que optimizan las utilidades",
      "SIN aproximaciones:", exterior.value)
print("Toneladas de pinturas para exteriores que optimizan las utilidades:",
      "%.2f"% exterior.value)
print("Toneladas de pinturas para interiores que optimizan las utilidades",
      "SIN aproximaciones:", interior.value)
print("Toneladas de pinturas para interiores que optimizan las utilidades:",
      "%.2f"% interior.value)

In [ ]:
# Solución matricial
# Escriba acá el código para resolver de forma matricial el ejercicio anterior


## Ejemplo 03: problema de la dieta

Tomado del libro de [TAHA, 2012](https://fad.unsa.edu.pe/bancayseguros/wp-content/uploads/sites/4/2019/03/investigacic3b3n-de-operaciones-9na-edicic3b3n-hamdy-a-taha-fl.pdf), ejemplo 2.1-1 página 24.

Variables de decisión:

X1: Libras de maíz en la mezcla diaria

X2: Libras de soya en la mezcla diaria

Función objetivo:		Minimizar Z=0,3X1+0,9X2

Restricciones:

Necesidades dietéticas de proteína		0,09X1+0,6X2 ≥0,3(X1+X2)

Necesidades dietéticas de fibra		0,02X1+0,06X2 ≤0,05(X1+X2)

Consumo mínimo de mezcla diaria		X1+X2≥800

No negatividad				X1, X2 ≥0


Organizando las ecuaciones se obtiene:

Necesidades dietéticas de proteína		0,21X1-0,30X2 ≤0

Necesidades dietéticas de fibra		0,03X1-0,01X2 ≥0

Consumo mínimo de mezcla diaria		X1+X2≥800

No negatividad				X1, X2 ≥0



In [ ]:
# Ejemplo 2.2-2 del libro de TAHA (Problema de la dieta)
# Solución algebraica

# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables a optimizar
maiz = cvx.Variable()
soya = cvx.Variable()

# Definir la función objetivo para minimizar el costo
objDieta = cvx.Minimize(0.3*maiz + 0.9*soya)

# Establecer las restricciones
restriccionesDieta = [

# Necesidades dietéticas de proteína
0.21*maiz - 0.3*soya <= 0,

# Necesidades dietéticas de fibra
0.03*maiz - 0.01*soya >= 0,

# Consumo mínimo de mezlca diaria
soya + maiz >= 800,

# Restricción de no negatividad
maiz >= 0,
soya >= 0
]

# Configurar el problema
probDieta = cvx.Problem(objDieta, restriccionesDieta)

# Obtener el valor óptimo
probDieta.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", probDieta.status)

# Mostrar el valor óptimo de la función objetivo sin aproximaciones
print("Costo mínimo SIN aproximaciones:", probDieta.value)

# Mostrar el valor óptimo de la función objetivo aproximado a dos decimales
print("Costo mínimo aproximada a dos decimales:", "%.2f"% probDieta.value, "\n")

# Mostrar los valores óptimos de las variables de decisión sin aproximaciones
print("Libras de maíz que minimizan el costo SIN aproximaciones:",
      maiz.value)
print("Libras de soya que minimizan el costo SIN aproximaciones:",
      soya.value, "\n")

# Mostrar valores óptimos de las variables de decisión aproximados
#a dos decimales
print("Libras de maíz que minimizan el costo aproximada a dos decimales:",
      "%.2f"%  maiz.value)
print("Libras de soya que minimizan el costo aproximada a dos decimales:",
      "%.2f"%  soya.value)

In [ ]:
# Solución matricial
# Escriba acá el código para resolver de forma matricial el ejercicio anterior



# Ejercicios

## Bank One

Resuelva con CVXPY el ejemplo 2.4-1 (Modelo de préstamo bancario) del libro de (TAHA, 2012) página 35.



In [ ]:
# Resuelva de forma matricial el ejercicio


## Hawaii Sugar Company

Resuelva con CVXPY el ejercicio 7 del libro de (TAHA, 2012) página 61.

In [ ]:
# Resuelva de forma matricial el ejercicio


## Control de contaminación

Resuelva con CVXPY el ejercicio 4 del libro de (TAHA, 2012) página 64.

In [ ]:
# Resuelva de forma matricial el ejercicio
